### ISSUE TITLE
Change nodeWalk() to find()

### ISSUE THREAD

**Issue by justinfagnani** [PolymerLabs/dom5#11]
To match `Element.find()` http://dev.w3.org/2006/webapi/selectors-api2/#find

**Comment by domenic** [comment]
Don't look at two-year-old drafts of discontinued specs...

These were replaced by `query` and `queryAll`: https://dom.spec.whatwg.org/#dom-parentnode-query

**Comment by justinfagnani** [comment]
Oops. Serves me right for just reading bad MDN docs and not the spec they linked to. It has both querySelector and find (with an experimental icon), so I figured it was upcoming.

`query`'s not a great name then, because `nodeWalk` takes a predicate, not a selector.
