### ISSUE TITLE
Why not just use jsdom?

### ISSUE THREAD

**Issue by domenic** [PolymerLabs/dom5#12]
As you duplicate more and more functionality, I was wondering why not just contribute to jsdom? Is it materially slower? (We made it possible to be much faster if you turn off script support, in 4.0.3.)

**Comment by justinfagnani** [comment]
jsdom tries to do too much, it acts like a browser. Mayeb I need to try 4.0.3. Last time I tried it it didn't work in newer versions of node because contextify failed to compile. I'd rather not depend on modules that are so fragile and bound to specific APIs on V8. All I want on top of parse5 is some utilities to query and modify it's AST. I also need these utilities in the browser.

(mini-rant: I can't believe that npm install is such a huge security hole by allowing local code execution like build scripts! I'm new to npm, but I immediately wanted to globally disable install hooks)

**Comment by azakus** [comment]
@domenic Maybe i'm missing something, but how do you turn off all script support?
All I see is the ability to turn off external scripts, but I'm worried about inline scripts being executed.

Also, I'm worried by dependence on iojs, when dom5 will work with node 0.10 and 0.12 as well as iojs.
Is that just for contextify support, or are there more fundamental JS features that being used that require iojs?

**Comment by domenic** [comment]
(To be clear, I don't really expect anyone to abandon this project; I'm more just looking for feedback on why jsdom doesn't meet your needs :)

It turns out that the word "external" in jsdom's options is a bit misleading. It generally means "in-DOM"---as opposed to "in io.js". If you turn off `ProcessExternalResources` for `script`, no `<script>` tags will run, ever. But you can still manipulate the DOM from io.js "scripts." (@Sebmaster can correct me if I'm misreading the code, since he made [the recent changes](https://github.com/tmpvar/jsdom/commit/7e7369e4fa81092e62f5c7fae7fc58e0169f6824).)

The dependency on io.js is for a bunch of stuff, but it basically breaks down into two categories: the new `vm` module, and a dependency on a V8 version that is not years old. That's important for a number of language features we rely on, e.g. `Set`, and likely soon `Symbol.toStringTag`. I can understand how it might be a deal-breaker for you guys though. The upside is, it no longer needs to compile anything, addressing @justinfagnani's concern :).

**Comment by justinfagnani** [comment]
Not compiling at install is certainly nicer :)

What would be even better to me is if jsdom were layered into multiple packages. The layer we're interested in would just wrap the parse5 AST in a DOM compatible API, without any resource loading or script execution. Then the more complete browser emulation about be built on top of that.

Keep us in the loop of changes and we'll take another look in the future. I'll close this for now.

**Comment by sthomp** [comment]
I'd just like to add here that its really nice how light dom5 is. I definitely appreciate the small number of dependencies (just 1 in this case).
